#!/bin/bash
echo "enter the values ino array"
read vehicle{}
echo "first type of vehicle is  ${vehicle[0]}"
echo "second type of vehicle is ${vehicle[1]}"
echo "third type of vehicle is  ${vehicle[2]}"
echo "fourth types of vehicles is ${vehicle[3]}"
echo "fifth type os vehicle is ${vehicle[4]}"
echo "all types of vehicles are ${vehicle[@]}"
