#!/bin/bash
echo "please enter user name"
read -s USERNAME
#echo "my user name is $USERNAME"
echo "plese enter password"
read -s PASSWORD
echo "my user name is $USERNAME"
echo "my password is $PASSWORD"